# ---------------------- Template Header ----------------------
AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for DynamoDB tables

# ---------------------- Parameters ----------------------
Parameters:
  EnvPrefix:
    Type: String
    Description: Prefix for naming DynamoDB tables (e.g., dev, test, prod)
    MinLength: 1

# ---------------------- Resources ----------------------
Resources:
  Itemstable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Sub: ${EnvPrefix}-Items
      AttributeDefinitions:
      - AttributeName: creationDate
        AttributeType: S
      - AttributeName: itemID
        AttributeType: S
      - AttributeName: seller
        AttributeType: S
      KeySchema:
      - AttributeName: itemID
        KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
      - IndexName: seller-creationDate-index
        KeySchema:
        - AttributeName: seller
          KeyType: HASH
        - AttributeName: creationDate
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 0
          WriteCapacityUnits: 0
  Transactionhistorytable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Sub: ${EnvPrefix}-TransactionHistory
      AttributeDefinitions:
      - AttributeName: buyerID
        AttributeType: S
      - AttributeName: sellerID
        AttributeType: S
      - AttributeName: transactionID
        AttributeType: S
      KeySchema:
      - AttributeName: transactionID
        KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
      - IndexName: buyerID-index
        KeySchema:
        - AttributeName: buyerID
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 0
          WriteCapacityUnits: 0
      - IndexName: sellerID-index
        KeySchema:
        - AttributeName: sellerID
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 0
          WriteCapacityUnits: 0
  Userstable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Sub: ${EnvPrefix}-Users
      AttributeDefinitions:
      - AttributeName: userID
        AttributeType: S
      - AttributeName: username
        AttributeType: S
      KeySchema:
      - AttributeName: username
        KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
      - IndexName: userID-index
        KeySchema:
        - AttributeName: userID
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 0
          WriteCapacityUnits: 0

# ---------------------- Outputs ----------------------
Outputs:
  Itemsarn:
    Description: ARN of Items table
    Value:
      Fn::GetAtt:
      - Itemstable
      - Arn
  Transactionhistoryarn:
    Description: ARN of TransactionHistory table
    Value:
      Fn::GetAtt:
      - Transactionhistorytable
      - Arn
  Usersarn:
    Description: ARN of Users table
    Value:
      Fn::GetAtt:
      - Userstable
      - Arn
