AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Full-stack deployment for Kashishop (core infrastructure):
  • Hosts frontend in S3 (with a public-read policy)
  • Creates DynamoDB tables (Items, TransactionHistory, Users) per JSON spec
  • Configures Cognito (User Pool, Client, Identity Pool, Admins group)

Parameters:
  EnvPrefix:
    Type: String
    Description: Prefix for naming resources (e.g., dev, test, prod)
    MinLength: 1

Resources:
  ########################################
  # 3) Cognito User Pool and Identity   #
  ########################################
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${EnvPrefix}-Kashishop"
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      MfaConfiguration: "OFF"
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          TemporaryPasswordValidityDays: 7
      UserPoolTags: {}

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub "${EnvPrefix}-KashishopClient"
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      PreventUserExistenceErrors: ENABLED

  CognitoUserPoolGroupAdmins:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: Admins
      UserPoolId: !Ref CognitoUserPool
      Description: "Administrators group"
      # If you do not need an IAM role attached, simply omit RoleArn:
      # RoleArn: arn:aws:iam::550295503037:role/AdminsRole

  CognitoIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: !Sub "${EnvPrefix}-KashishopIdentityPool"
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId: !Ref CognitoUserPoolClient
          ProviderName: !GetAtt CognitoUserPool.ProviderName
          ServerSideTokenCheck: true
    DeletionPolicy: Retain

Outputs:
  WebsiteURL:
    Description: URL for the homepage (index.html) of the static website
    Value: !Sub "http://${EnvPrefix}-kashishop-frontend.s3-website-${AWS::Region}.amazonaws.com/index.html"